### ISSUE TITLE
No message indicating success or failure of export to json

### ISSUE THREAD

**Issue by elliottpicker** [gin-nader/MSCS721-roomScheduler#3]
After creating a few rooms I attempted to export the data to a json file. I was presented with the json string itself, but no verbage indicating the result of the operation. I would expect a message of some sort.
This was done on windows 10 java version "1.8.0_121"  git commit afS5352 Feb 24, 2017 
Steps to recreate
option 1 – Add several rooms
option 6 – export to json

This is a feature request.

**Comment by gin-nader** [comment]
Fixed
