### ISSUE TITLE
No acknowledgement to import from json

### ISSUE THREAD

**Issue by elliottpicker** [gin-nader/MSCS721-roomScheduler#4]
When reading in my recently exported room data I recievied my original menu prompt, I don't know if import was done. I would expect to be told what happened in some way. 
This was done on windows 10 java version "1.8.0_121"  git commit afS5352 Feb 24, 2017 
Steps to recreate
option 7 - import from JSON

This is a feature request.

**Comment by gin-nader** [comment]
Fixed
